name: todo_sensor_tracking_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  lottie: ^3.1.2
  sensors_plus: ^6.0.1
  syncfusion_flutter_charts: ^26.2.14
  flutter_animate: ^4.5.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/png/
    - assets/json/

